name: build

on: [push]

jobs:
  cmake-build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: install dependencies
      run: >
        sudo apt update -y &&
        sudo apt install -y cmake build-essential libpcap-dev qt5-default qtdeclarative5-dev libqt5charts5-dev
    - name: cmake build 
      run: >
        mkdir build && 
        cd build && 
        cmake .. && 
        make -j5
