name: build

on: [push]

jobs:
  cmake-build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        dir: '${{ github.workspace }}/example/'
        modules: 'qtcharts'
        archives: 'qtbase qtdeclarative'
    
    - name: Install other dependencies
      run: >
        sudo apt update -y &&
        sudo apt install -y 
          cmake 
          libpcap-dev
    - name: Cmake build 
      run: >
        mkdir build && 
        cd build && 
        cmake .. && 
        make -j5
    
