name: build

on: [push]

jobs:
  cmake-build:

    runs-on: ubuntu-latest

    steps:    
    # install packages
    # deb http://archive.ubuntu.com/ubuntu/ jammy main restricted 
    # deb http://archive.ubuntu.com/ubuntu/ jammy universe
    
    # https://github.com/ryankurte/action-apt
    
    - name: Add debian repository
      uses: myci-actions/add-deb-repo@10
      with:
        install: >
          cmake 
          qtbase5-dev 
          qml-module-qtquick-controls
          libqt5gui5 
          libqt5charts5-dev 
          qtdeclarative5-dev 
          libpcap-dev
          
    - uses: actions/checkout@v3
    - run: >
        mkdir build && 
        cd build && 
        cmake .. && 
        make -j5
    
